[tools]
#ag = "latest"
#openspec = "latest"
#python = "latest"
cheat = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
node = "latest"
opencode = "latest"
rclone = "latest"
uv = "latest"
vim = "latest"
yazi = "latest"
yt-dlp = "latest"
zellij = "latest"
zoxide = "latest"
